variables:
    NAT_SG_NAME:
        required: true
        description: the name of the security group to create for the NAT
        default: "NAT-sg"
    VPC_NAME:
        required: true
        description: the name of the VPC
    NAT_INGRESS_PORTS:
        required: true
        description: allowed ingress ports on the nat
        default:
            - "80"
            - "443"
    NAT_INGRESS_CIDRS:
        required: true
        description: allowed ingress network cidrs on the nat
        default :
            - "0.0.0.0/0"
    NAT_EGRESS_PORTS:
        required: true
        description: allowed ingress ports on the nat
        default:
            - "0..65535"
    NAT_EGRESS_CIDRS:
        required: true
        description: allowed ingress network cidrs on the nat
        default :
            - "0.0.0.0/0"
    NAT_NAME:
        required: true
        description: the name of the nat instance
        default: "NAT"
    NAT_AMI:
        required: true
        description: the ami id of the nat
        default: "ami-ad227cc4"
    NAT_SIZE:
        required: true
        description: the instance size of the nat
        default: "m1.small"
    PUBLIC_SUBNET_NAME:
        required: true
        description: the cloudcoreo name of the public vpc subnets